name: nc-ttp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3
  - numpy>=1.21
  - scipy>=1.7
  - matplotlib>=3.4
  - lifelines>=0.27
  - scikit-learn>=1.0
  - jupyterlab>=3.0
  - notebook>=6.4
  - ipykernel
  - nb_conda_kernels
  - pip
  - seaborn>=0.11
  - statsmodels>=0.13
  - shap